// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fileops.proto

package fileops

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OpenRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{0}
}
func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (dst *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(dst, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type OpenResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{1}
}
func (m *OpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenResponse.Unmarshal(m, b)
}
func (m *OpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenResponse.Marshal(b, m, deterministic)
}
func (dst *OpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenResponse.Merge(dst, src)
}
func (m *OpenResponse) XXX_Size() int {
	return xxx_messageInfo_OpenResponse.Size(m)
}
func (m *OpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenResponse proto.InternalMessageInfo

func (m *OpenResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CloseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{2}
}
func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (dst *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(dst, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

type CloseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{3}
}
func (m *CloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponse.Unmarshal(m, b)
}
func (m *CloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponse.Marshal(b, m, deterministic)
}
func (dst *CloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponse.Merge(dst, src)
}
func (m *CloseResponse) XXX_Size() int {
	return xxx_messageInfo_CloseResponse.Size(m)
}
func (m *CloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponse proto.InternalMessageInfo

type ReadAtRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	BlockSize            int64    `protobuf:"varint,3,opt,name=BlockSize,proto3" json:"BlockSize,omitempty"`
	ReadSize             int64    `protobuf:"varint,4,opt,name=ReadSize,proto3" json:"ReadSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAtRequest) Reset()         { *m = ReadAtRequest{} }
func (m *ReadAtRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAtRequest) ProtoMessage()    {}
func (*ReadAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{4}
}
func (m *ReadAtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAtRequest.Unmarshal(m, b)
}
func (m *ReadAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAtRequest.Marshal(b, m, deterministic)
}
func (dst *ReadAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAtRequest.Merge(dst, src)
}
func (m *ReadAtRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAtRequest.Size(m)
}
func (m *ReadAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAtRequest proto.InternalMessageInfo

func (m *ReadAtRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadAtRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadAtRequest) GetBlockSize() int64 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *ReadAtRequest) GetReadSize() int64 {
	if m != nil {
		return m.ReadSize
	}
	return 0
}

type Chunk struct {
	Offset               int64    `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{5}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (dst *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(dst, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Chunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SizeRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeRequest) Reset()         { *m = SizeRequest{} }
func (m *SizeRequest) String() string { return proto.CompactTextString(m) }
func (*SizeRequest) ProtoMessage()    {}
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{6}
}
func (m *SizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeRequest.Unmarshal(m, b)
}
func (m *SizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeRequest.Marshal(b, m, deterministic)
}
func (dst *SizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeRequest.Merge(dst, src)
}
func (m *SizeRequest) XXX_Size() int {
	return xxx_messageInfo_SizeRequest.Size(m)
}
func (m *SizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SizeRequest proto.InternalMessageInfo

func (m *SizeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SizeResponse struct {
	Size                 int64    `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeResponse) Reset()         { *m = SizeResponse{} }
func (m *SizeResponse) String() string { return proto.CompactTextString(m) }
func (*SizeResponse) ProtoMessage()    {}
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{7}
}
func (m *SizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeResponse.Unmarshal(m, b)
}
func (m *SizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeResponse.Marshal(b, m, deterministic)
}
func (dst *SizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeResponse.Merge(dst, src)
}
func (m *SizeResponse) XXX_Size() int {
	return xxx_messageInfo_SizeResponse.Size(m)
}
func (m *SizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SizeResponse proto.InternalMessageInfo

func (m *SizeResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReaderAtRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	ReadSize             int64    `protobuf:"varint,2,opt,name=ReadSize,proto3" json:"ReadSize,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaderAtRequest) Reset()         { *m = ReaderAtRequest{} }
func (m *ReaderAtRequest) String() string { return proto.CompactTextString(m) }
func (*ReaderAtRequest) ProtoMessage()    {}
func (*ReaderAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{8}
}
func (m *ReaderAtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaderAtRequest.Unmarshal(m, b)
}
func (m *ReaderAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaderAtRequest.Marshal(b, m, deterministic)
}
func (dst *ReaderAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaderAtRequest.Merge(dst, src)
}
func (m *ReaderAtRequest) XXX_Size() int {
	return xxx_messageInfo_ReaderAtRequest.Size(m)
}
func (m *ReaderAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaderAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReaderAtRequest proto.InternalMessageInfo

func (m *ReaderAtRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReaderAtRequest) GetReadSize() int64 {
	if m != nil {
		return m.ReadSize
	}
	return 0
}

func (m *ReaderAtRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ReaderAtResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaderAtResponse) Reset()         { *m = ReaderAtResponse{} }
func (m *ReaderAtResponse) String() string { return proto.CompactTextString(m) }
func (*ReaderAtResponse) ProtoMessage()    {}
func (*ReaderAtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fileops_1c3d6650fce37a42, []int{9}
}
func (m *ReaderAtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaderAtResponse.Unmarshal(m, b)
}
func (m *ReaderAtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaderAtResponse.Marshal(b, m, deterministic)
}
func (dst *ReaderAtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaderAtResponse.Merge(dst, src)
}
func (m *ReaderAtResponse) XXX_Size() int {
	return xxx_messageInfo_ReaderAtResponse.Size(m)
}
func (m *ReaderAtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaderAtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReaderAtResponse proto.InternalMessageInfo

func (m *ReaderAtResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenRequest)(nil), "fileops.OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "fileops.OpenResponse")
	proto.RegisterType((*CloseRequest)(nil), "fileops.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "fileops.CloseResponse")
	proto.RegisterType((*ReadAtRequest)(nil), "fileops.ReadAtRequest")
	proto.RegisterType((*Chunk)(nil), "fileops.Chunk")
	proto.RegisterType((*SizeRequest)(nil), "fileops.SizeRequest")
	proto.RegisterType((*SizeResponse)(nil), "fileops.SizeResponse")
	proto.RegisterType((*ReaderAtRequest)(nil), "fileops.ReaderAtRequest")
	proto.RegisterType((*ReaderAtResponse)(nil), "fileops.ReaderAtResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileOpsServiceClient is the client API for FileOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileOpsServiceClient interface {
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	StreamReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (FileOpsService_StreamReadAtClient, error)
	Size(ctx context.Context, in *SizeRequest, opts ...grpc.CallOption) (*SizeResponse, error)
	ReaderAt(ctx context.Context, in *ReaderAtRequest, opts ...grpc.CallOption) (*ReaderAtResponse, error)
}

type fileOpsServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileOpsServiceClient(cc *grpc.ClientConn) FileOpsServiceClient {
	return &fileOpsServiceClient{cc}
}

func (c *fileOpsServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, "/fileops.FileOpsService/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileOpsServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, "/fileops.FileOpsService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileOpsServiceClient) StreamReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (FileOpsService_StreamReadAtClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileOpsService_serviceDesc.Streams[0], "/fileops.FileOpsService/StreamReadAt", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileOpsServiceStreamReadAtClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileOpsService_StreamReadAtClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type fileOpsServiceStreamReadAtClient struct {
	grpc.ClientStream
}

func (x *fileOpsServiceStreamReadAtClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileOpsServiceClient) Size(ctx context.Context, in *SizeRequest, opts ...grpc.CallOption) (*SizeResponse, error) {
	out := new(SizeResponse)
	err := c.cc.Invoke(ctx, "/fileops.FileOpsService/Size", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileOpsServiceClient) ReaderAt(ctx context.Context, in *ReaderAtRequest, opts ...grpc.CallOption) (*ReaderAtResponse, error) {
	out := new(ReaderAtResponse)
	err := c.cc.Invoke(ctx, "/fileops.FileOpsService/ReaderAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileOpsServiceServer is the server API for FileOpsService service.
type FileOpsServiceServer interface {
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	StreamReadAt(*ReadAtRequest, FileOpsService_StreamReadAtServer) error
	Size(context.Context, *SizeRequest) (*SizeResponse, error)
	ReaderAt(context.Context, *ReaderAtRequest) (*ReaderAtResponse, error)
}

func RegisterFileOpsServiceServer(s *grpc.Server, srv FileOpsServiceServer) {
	s.RegisterService(&_FileOpsService_serviceDesc, srv)
}

func _FileOpsService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileOpsServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileops.FileOpsService/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileOpsServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileOpsService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileOpsServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileops.FileOpsService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileOpsServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileOpsService_StreamReadAt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadAtRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileOpsServiceServer).StreamReadAt(m, &fileOpsServiceStreamReadAtServer{stream})
}

type FileOpsService_StreamReadAtServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type fileOpsServiceStreamReadAtServer struct {
	grpc.ServerStream
}

func (x *fileOpsServiceStreamReadAtServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func _FileOpsService_Size_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileOpsServiceServer).Size(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileops.FileOpsService/Size",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileOpsServiceServer).Size(ctx, req.(*SizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileOpsService_ReaderAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReaderAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileOpsServiceServer).ReaderAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fileops.FileOpsService/ReaderAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileOpsServiceServer).ReaderAt(ctx, req.(*ReaderAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileOpsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fileops.FileOpsService",
	HandlerType: (*FileOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _FileOpsService_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _FileOpsService_Close_Handler,
		},
		{
			MethodName: "Size",
			Handler:    _FileOpsService_Size_Handler,
		},
		{
			MethodName: "ReaderAt",
			Handler:    _FileOpsService_ReaderAt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReadAt",
			Handler:       _FileOpsService_StreamReadAt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fileops.proto",
}

func init() { proto.RegisterFile("fileops.proto", fileDescriptor_fileops_1c3d6650fce37a42) }

var fileDescriptor_fileops_1c3d6650fce37a42 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0xa5, 0xa0, 0x8c, 0xa5, 0x98, 0x89, 0x92, 0xda, 0x18, 0xa3, 0x7b, 0x30, 0x9e, 0x88,
	0x91, 0x98, 0x18, 0x6f, 0x88, 0x31, 0xe1, 0x84, 0x29, 0x27, 0x8f, 0x15, 0x86, 0xd0, 0x50, 0x69,
	0x6d, 0x8b, 0x07, 0x7f, 0xcc, 0xdf, 0x33, 0x3b, 0x2d, 0xec, 0x96, 0x28, 0xb7, 0x9d, 0x9d, 0xd9,
	0xf7, 0xde, 0xbc, 0xd7, 0x42, 0x7b, 0x1e, 0x46, 0x14, 0x27, 0x59, 0x2f, 0x49, 0xe3, 0x3c, 0xc6,
	0x83, 0xb2, 0x14, 0x57, 0x70, 0x34, 0x4e, 0x68, 0xe5, 0xd3, 0xe7, 0x9a, 0xb2, 0x1c, 0x11, 0xac,
	0xd7, 0x20, 0x5f, 0xb8, 0xc6, 0xa5, 0x71, 0xd3, 0xf2, 0xf9, 0x2c, 0x2e, 0xc0, 0x2e, 0x46, 0xb2,
	0x24, 0x5e, 0x65, 0x84, 0x0e, 0x98, 0xa3, 0x19, 0x4f, 0xd4, 0x7d, 0x73, 0x34, 0x13, 0x0e, 0xd8,
	0xc3, 0x28, 0xce, 0xa8, 0xc4, 0x10, 0x1d, 0x68, 0x97, 0x75, 0xf1, 0x40, 0xac, 0xa1, 0xed, 0x53,
	0x30, 0x1b, 0xe4, 0x7b, 0x58, 0xb0, 0x0b, 0xcd, 0xf1, 0x7c, 0x9e, 0x51, 0xee, 0x9a, 0x8c, 0x5c,
	0x56, 0x78, 0x0e, 0xad, 0xa7, 0x28, 0x9e, 0x2e, 0x27, 0xe1, 0x37, 0xb9, 0x75, 0x6e, 0xa9, 0x0b,
	0xf4, 0xe0, 0x50, 0x42, 0x73, 0xd3, 0xe2, 0xe6, 0xb6, 0x16, 0x7d, 0x68, 0x0c, 0x17, 0xeb, 0xd5,
	0x52, 0x83, 0x36, 0x2a, 0xd0, 0x08, 0xd6, 0x73, 0x90, 0x07, 0x4c, 0x68, 0xfb, 0x7c, 0x96, 0x7e,
	0xc8, 0xc7, 0xfb, 0xfc, 0x10, 0x60, 0x17, 0x23, 0xa5, 0x1f, 0x08, 0x16, 0xf3, 0x17, 0xe0, 0x7c,
	0x16, 0x6f, 0xd0, 0x91, 0x3a, 0x28, 0x55, 0x4b, 0xff, 0xa7, 0x42, 0x5f, 0xc1, 0xac, 0xae, 0xb0,
	0xa5, 0xaf, 0x6b, 0xf4, 0xd7, 0x70, 0xac, 0xa0, 0x95, 0x04, 0xde, 0xc4, 0x50, 0x9b, 0xdc, 0xfd,
	0x98, 0xe0, 0xbc, 0x84, 0x11, 0x8d, 0x93, 0x6c, 0x42, 0xe9, 0x57, 0x38, 0x25, 0xbc, 0x07, 0x4b,
	0x26, 0x89, 0x27, 0xbd, 0xcd, 0xd7, 0xa0, 0x65, 0xef, 0x9d, 0xee, 0xdc, 0x96, 0xe9, 0xd5, 0xf0,
	0x01, 0x1a, 0x1c, 0x28, 0xaa, 0x09, 0x3d, 0x70, 0xaf, 0xbb, 0x7b, 0xbd, 0x7d, 0xf9, 0x08, 0xf6,
	0x24, 0x4f, 0x29, 0xf8, 0x28, 0xf2, 0x47, 0x35, 0x59, 0xf9, 0x20, 0x3c, 0x47, 0x21, 0xc8, 0xc4,
	0x44, 0xed, 0xd6, 0x90, 0x62, 0xd9, 0x03, 0x25, 0x56, 0x0b, 0x46, 0x13, 0xab, 0x67, 0x21, 0x6a,
	0x38, 0x28, 0xec, 0x94, 0xf6, 0xa0, 0x5b, 0xa1, 0xd3, 0xc2, 0xf0, 0xce, 0xfe, 0xe8, 0x6c, 0x20,
	0xde, 0x9b, 0xfc, 0x8f, 0xf4, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xac, 0x26, 0xe0, 0x58, 0x34,
	0x03, 0x00, 0x00,
}
