// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CloseRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCloseRequest(buf []byte, offset flatbuffers.UOffsetT) *CloseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CloseRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CloseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CloseRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func CloseRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func CloseRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
