// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CloseRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCloseRequest(buf []byte, offset flatbuffers.UOffsetT) *CloseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CloseRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CloseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CloseRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CloseRequest) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CloseRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CloseRequestAddPath(builder *flatbuffers.Builder, Path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Path), 0)
}
func CloseRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
