// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpenResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsOpenResponse(buf []byte, offset flatbuffers.UOffsetT) *OpenResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpenResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpenResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpenResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OpenResponse) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OpenResponse) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func OpenResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OpenResponseAddId(builder *flatbuffers.Builder, Id int64) {
	builder.PrependInt64Slot(0, Id, 0)
}
func OpenResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
