// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpenRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsOpenRequest(buf []byte, offset flatbuffers.UOffsetT) *OpenRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpenRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpenRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpenRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OpenRequest) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OpenRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OpenRequestAddPath(builder *flatbuffers.Builder, Path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Path), 0)
}
func OpenRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
