// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReadAtResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsReadAtResponse(buf []byte, offset flatbuffers.UOffsetT) *ReadAtResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReadAtResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReadAtResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReadAtResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReadAtResponse) Offset() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReadAtResponse) MutateOffset(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *ReadAtResponse) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ReadAtResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReadAtResponseAddOffset(builder *flatbuffers.Builder, Offset int64) {
	builder.PrependInt64Slot(0, Offset, 0)
}
func ReadAtResponseAddData(builder *flatbuffers.Builder, Data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Data), 0)
}
func ReadAtResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
