// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SizeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSizeRequest(buf []byte, offset flatbuffers.UOffsetT) *SizeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SizeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SizeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SizeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SizeRequest) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SizeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SizeRequestAddPath(builder *flatbuffers.Builder, Path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Path), 0)
}
func SizeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
