// automatically generated by the FlatBuffers compiler, do not modify

package fileoperations

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SizeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSizeResponse(buf []byte, offset flatbuffers.UOffsetT) *SizeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SizeResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SizeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SizeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SizeResponse) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SizeResponse) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func SizeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SizeResponseAddSize(builder *flatbuffers.Builder, Size int64) {
	builder.PrependInt64Slot(0, Size, 0)
}
func SizeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
